package com.tcejorptset.servl.controller;

public enum CommandName {
	GO_TO_BASE_PAGE, 
	GO_TO_LOGINATION_PAGE, 
	GO_TO_NEWS_LIST, 
	GO_TO_VIEW_NEWS,
	GO_TO_ADD_EDIT_NEWS_PAGE,
	GO_TO_ERROR_PAGE,
	DO_SIGN_IN,
	DO_SIGN_OUT,
	DO_REGISTRATION,
	DO_CHANGE_LOCALE,
	DO_ADD_NEWS,
	DO_EDIT_NEWS,
	DO_DELETE_NEWS
}
